[tool.poetry]
name = "SuperLesson"
version = "0.1.0"
description = "CLI to transcribe lectures"
authors = [
    "Isabella Basso",
    "Felipe Kaneshiro",
    "Isaque Alves",
    "Ricardo Saraiva",
]
packages = [{ include = "superlesson" }]
readme = "README.md"
license = "MIT"
repository = "https://github.com/SuperLesson/SuperLesson"

[tool.poetry.scripts]
superlesson = "superlesson:main"
transcribe = "superlesson:transcribe_step"
tmarks = "superlesson:tmarks_step"
verify = "superlesson:verify_step"
replace = "superlesson:replace_step"
improve = "superlesson:improve_step"
annotate = "superlesson:annotate_step"

[tool.poetry.dependencies]
python = "^3.9"
typst = "^0.8.0"

[tool.poetry.group.transcribe.dependencies]
faster-whisper = "^0.9.0"
tqdm = "^4.66.1"

[tool.poetry.group.tmarks.dependencies]
pydub = "^0.25.1"

[tool.poetry.group.verify.dependencies]
python-mpv = "^1.0.4"

[tool.poetry.group.improve.dependencies]
python-dotenv = "^1.0.0"
openai = "^0.28.1"
tiktoken = "^0.5.1"

[tool.poetry.group.annotate.dependencies]
pypdf = { extras = ["crypto"], version = "^3.16.2" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
hypothesis = "^6.87.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
