[tool.poetry]
name = "SuperLesson"
version = "0.1.0"
description = "CLI to transcribe lectures"
authors = ["Isabella Basso", "Felipe Kaneshiro", "Isaque Alves", "Ricardo Saraiva"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"
faster-whisper = "^0.8.0"
openai = "^0.28.1"
pydub = "^0.25.1"
pypdf = {extras = ["crypto"], version = "^3.16.2"}
ffmpeg-python = "^0.2.0"
python-dotenv = "^1.0.0"
python-mpv = "^1.0.4"
pytest = "^7.4.2"
hypothesis = "^6.88.1"
tiktoken = "^0.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
